name = "flowmi-docs"
compatibility_date = "2025-03-10"

routes = [
  { pattern = "flowmi.ai/docs*", zone_name = "flowmi.ai" },
  { pattern = "flowmi.ai/blogs*", zone_name = "flowmi.ai" }
]

[assets]
directory = "./dist"
